config/routes.rb
Weatherham::Application.routes.draw do
  get "observations/index"

 # match '/javascripts/:action.js' => 'javascripts#index', :as => :javascript, :format => :js
  resources :observations do
    collection do
      get :statistics
    end
  end

  match '/observations/range/:range_begin/:range_end/:granularity.:format' => 'observations#range',
      as: :range, constraints: { granularity: /five_min|hourly|six_hour|daily/ }
  match '/changelog(.:format)' => 'pages#changelog', as: :changelog
  match '/todo(.:format)' => 'pages#todo', as: :todo
  match '/about(.:format)' => 'pages#about', as: :about

  root to: 'observations#index'

end

app/models/observation.rb
class Observation < ActiveRecord::Base
  attr_accessible :barometer, :created_at, :dew_point, :hi_dir, :hi_speed, :hi_temp, :humidity, :low_temp, :observed_at, :rain, :temp, :updated_at, :wind_chill, :wind_dir, :wind_run, :wind_speed

  scope :ordered, order('observed_at ASC')

  def self.prune!
    max = 9000
    if count > max
      Observation.ordered.limit(count - max).destroy_all
    end
  end

  cattr_accessor :displayed_attributes, :other_attributes
  @@displayed_attributes = %w( wind_speed hi_speed temp barometer humidity wind_chill dew_point rain )
  @@other_attributes = { wind_speed: :wind_dir, hi_speed: :hi_dir }

  def self.current_barometer_direction
    recent_barometer_average = where(observed_at: (last.observed_at - 6.hours)..last.observed_at).average :barometer
    last.barometer < recent_barometer_average ? :down : :up
  end

  def self.need_fetch?
    return true unless Observation.any?
    Observation.select('id, observed_at').last.observed_at < 7.minutes.ago
  end

  def rain
    r = read_attribute(:rain)
    r * 25.4 if r # To MM
  end

  # Theoretically shared


  scope :only_id, select('id')
  scope :only_time, select('id, observed_at')
  validates_presence_of :observed_at

  # if base != Observation then
  #   def base.displayed_attributes
  #     Observation.displayed_attributes
  #   end

  #   def base.other_attributes
  #     Observation.other_attributes
  #   end
  # end

  def self.observed_at(where, options = {})
    only_time.send(where, options).try(:observed_at)
  end

  # class setter getters

  def self.period(p = nil)
    p.nil? ? @period : @period = p
  end

  def self.zoom(t = nil)
    t.nil? ? @zoom : @zoom = t
  end


  def observed_at_for_flot
    observed_at.to_i * 1000
  end

  def attribute_pair_for_plot(attribute)
    [ self.observed_at_for_flot, self.send(attribute) ]
  end



  period 5.minutes
  zoom 1.day

end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  GRANULARITIES = {
    five_min: Observation,
    # hourly: HourlyObservation,
    # six_hour: SixHourObservation,
    # daily: DailyObservation,
  }.with_indifferent_access.freeze


  def index
    Fetch.start! if Observation.first.nil?

    @last_observation = Observation.last
    @barometer_direction = Observation.current_barometer_direction if @last_observation
    @granularities = GRANULARITIES.keys
  end


  def show
    if Observation.need_fetch? && Rails.env.production?
      Rails.logger.warn("Needing a fetch now")
      Observation.prune! # We should just prune all the time
      Fetch.start!
    else
      Rails.logger.warn("No need for a fetch, just server up the db")
    end

    klass = GRANULARITIES[params[:id]]
    if stale?(fresh_options(klass.last))

      @ranges = {
        barometer: {
          max: klass.maximum(:barometer),
          min: klass.minimum(:barometer)
        },
        max: %w( hi_speed temp humidity ).collect{|a| klass.maximum a }.max
      }

      n = klass.zoom / klass.period
      @observations = klass.ordered.limit(n).offset([klass.count - n, 0].max).all
    end
  end

  def range
    klass = GRANULARITIES[params[:granularity]]
    range = Time.from_json(params[:range_begin]) .. Time.from_json(params[:range_end])
    if stale?(etag: Digest::SHA1.hexdigest("#{klass}/#{range}"))
      @observations = klass.where(observed_at: range).all
      render 'show'
    end
  end

  def statistics
    # {"observation":{"wind_dir":"SSE","temp":54.2,"low_temp":null,"hi_speed":27.0,"observed_at":"2010-04-27T11:10:00-07:00","humidity":71,"created_at":"2010-04-27T11:14:47-07:00","barometer":29.378,"updated_at":"2010-04-27T11:14:47-07:00","wind_chill":47.6,"wind_speed":16.0,"id":33531,"hi_dir":"SSE","wind_run":1.33,"hi_temp":null,"dew_point":45.0}}
    @statistics = Observation.statistics
    respond_to do |with|
      with.xml { render xml: @statistics }
      with.json { render json: @statistics }
    end
  end

end

app/helpers/observations_helper.rb
module ObservationsHelper
  def plot(name)
    content_tag :div, '', id: name, class: 'flot'
  end

  def metric_toggler(name, icon_name, options = {})
    icon = icon(icon_name)
    options[:default] = true if options[:default].nil?
    options[:class] ||= ''
    options[:class] << ' ' + name.to_s
    options[:class] << (options[:default] ? " default_on" : " default_off")
    content_tag :div, check_box_with_label(name, icon), :class => "metric_toggler #{options[:class]}"
  end

  def check_box_with_label(name, icon)
    content_tag :label, icon + check_box_tag(name) + t(:"attributes.#{name}.title", :default => name.titleize), :for => name
  end

  def attribute_pairs_for_plot(observations, attribute)
    observations.collect{|o| o.attribute_pair_for_plot(attribute) }
  end

  def data_for_plot
    Hash.new.tap do |data|
      return nil if @observations.size.zero?

      data[:plot_pairs] = Observation.displayed_attributes.each_with_object({}) do |attr, hash|
        hash[attr] = attribute_pairs_for_plot(@observations, attr)
      end

      data[:times] = @observations.each_with_object({}) do |observation, hash|
        hash[observation.observed_at_for_flot] = observation.attributes.reject{|k,v| ! Observation.other_attributes.values.include? k.to_sym }
      end

      data[:mappings] = Observation.other_attributes
      data[:earliest_point] = @observations.first.observed_at_for_flot
      data[:latest_point] = @observations.last.observed_at_for_flot
      data[:yaxis_ranges] = @ranges
      p data.keys, data[:yaxis_ranges]
    end
  end

  # TODO: this appears to be unused
  def iphone_observation(field, options = {})
    content_tag(:li,
      content_tag(:span, options[:label] || t(:"attributes.#{field}.title"), :class => 'label') +
      content_tag(:small,
        @last_observation.send(field).to_s +
        content_tag(:span, options[:unit] || t(:"attributes.#{field}.unit"), :class => 'counter_label'),
      :class => 'counter')
    )
  end

  def direction_to_html(direction)
    @_direction_entities ||= {
      up: '&uarr;',
      down: '&darr;',
    }

    @_direction_entities.fetch(direction, '').html_safe
  end

  private

  def icon(name)
    content_tag :i, nil, class: "wi wi-#{name}"
  end
end

app/views/observations/_observation.html.erb
<% div_for observation do %>
	<h3><%= observation.observed_at.to_s :long %></h3>
	<%= [:temp, :wind_speed, :wind_dir, :hi_speed, :hi_dir, :barometer].collect{|a| "#{a}: #{observation.send(a)}. " } %>
<% end %>

app/views/observations/changelog.erb
<div id="changelog">
	<%= @changelog %>
</div>

app/views/observations/index.html.erb
<% js_vars_with_scope :paths do %>
  <% @granularities.each do |granularity| %>
    <% js_var granularity, observation_path(granularity, :format => :json) %>
  <% end %>
<% end %>

<div class="granularity_switcher">
  <%#= link_to_function 'Day',   '$.weatherham("five_min")' %>
  <%#= link_to_function 'Week',  '$.weatherham("hourly")' %>
  <%#= link_to_function 'Month', '$.weatherham("six_hour")' %>
  <%#= link_to_function 'Year',  '$.weatherham("daily")' %>
</div>

<% if @last_observation %>
  <p>Last Observation at <strong id="last_observation"><%=l @last_observation.observed_at, :format => :long %></strong>. Barometer: <%= @last_observation.barometer %> <%= direction_to_html @barometer_direction %></p>
<% end %>

<%= plot :weather %>

<form action="/" class="metrics">
  <%= metric_toggler 'wind_speed', 'windy' %>
  <%= metric_toggler 'hi_speed', 'cloudy-gusts' %>
  <%= metric_toggler 'temp', 'thermometer' %>
  <%= metric_toggler 'wind_chill', 'snowflake-cold', :default => false %>
  <%= metric_toggler 'barometer', 'barometer' %>
  <%= metric_toggler 'humidity', 'humidity', :default => false %>
  <%= metric_toggler 'dew_point', 'raindrops', :default => false %>
  <%= metric_toggler 'rain', 'rain', :default => false %>
</form>

app/views/observations/index.iphone.erb
<div id="home" class="current">
    <div class="toolbar">
        <h1>Weatherham</h1>
    </div>
    <h2><%=l @last_observation.observed_at, :format => :long %></h2>
    <ul class="rounded">
				<%= iphone_observation :temp %>
				<%= iphone_observation :wind_speed %>
				<%= iphone_observation :barometer, :unit => direction_to_html(@barometer_direction) %>
    </ul>
    <h2>More Information</h2>
    <ul class="rounded">
        <li class="arrow"><a href="#current">Current Conditions</a></li>
        <!-- <li class="arrow"><a href="#current">Hourly</a></li>
        <li class="arrow"><a href="#current">Today</a></li> -->
    </ul>    
    <div class="info">
			<p>
				Created by <%= link_to 'Amiel Martin', 'http://amielmartin.com' %>.
				Weather data provided by <%= link_to 'Bellingham Cold Storage', 'http://www.bellcold.com/download.txt' %>.
			</p>
			<p><%= link_to 'full site', 'http://weatherham.com' %></p>
		</div>
</div>
<div id="current">
    <div class="toolbar">
        <h1>Current</h1>
        <a class="back" href="#home">Back</a>
    </div>
    <ul class="edgetoedge">
      <li class="sep">Temperature</li>
			<%= iphone_observation :temp, :label => 'Ambient' %>
			<%= iphone_observation :wind_chill %>
      <li class="sep">Wind</li>
			<%= iphone_observation :wind_speed, :label => 'Speed' %>
			<%= iphone_observation :hi_speed %>
			<%= iphone_observation :wind_dir %>
			<li class="sep">Other</li>
			<%= iphone_observation :dew_point %>
			<%= iphone_observation :humidity %>
    </ul>
    <div class="info">
			<p>
				Created by <%= link_to 'Amiel Martin', 'http://amielmartin.com' %>.
				Weather data provided by <%= link_to 'Bellingham Cold Storage', 'http://www.bellcold.com/download.txt' %>.
			</p>
			<p><%= link_to 'full site', 'http://weatherham.com' %></p>
		</div>
</div>

app/views/observations/index.json.erb
<%= @observations.collect(&:to_h).to_json %>

app/views/observations/show.json.erb
<%= raw data_for_plot.to_json %>

app/views/observations/todo.erb
<div id="todo">
	<%= @todo %>
</div>