config/routes.rb
Weatherham::Application.routes.draw do
  get "observations/index"

 # match '/javascripts/:action.js' => 'javascripts#index', :as => :javascript, :format => :js
  resources :observations do
    collection do
      get :statistics
    end
  end

  match '/observations/range/:range_begin/:range_end/:granularity.:format' => 'observations#range',
      as: :range, constraints: { granularity: /five_min|hourly|six_hour|daily/ }
  match '/changelog(.:format)' => 'pages#changelog', as: :changelog
  match '/todo(.:format)' => 'pages#todo', as: :todo
  match '/about(.:format)' => 'pages#about', as: :about

  root to: 'observations#index'

end

app/helpers/layout_helper.rb
module LayoutHelper
  def body_class
    "#{controller.controller_name} #{controller.controller_name}-#{controller.action_name}"
  end

  def render_title
    title = @_title || @content_for_title
    if title then
      "#{title} - #{t('site_name')}"
    else
      "#{t(:site_name)} - #{t(:slogan)}"
    end
  end

  def title(str)
    @_title = str
  end


  def javascript(name)
    content_for(:javascript) { sprockets_include_tag name }
  end

  def stylesheet(name)
    content_for(:head) { stylesheet_link_tag name }
  end
end

app/views/layouts/_flashes.html.erb
<% flashes_to_show = ([ :error, :warning, :notice ] << flash[:show]).flatten.compact.uniq %>
<% unless flashes_to_show.collect{|e|flash[e]}.compact.empty? %>
	<div class="panel" id="flash_panel">
		<div class="content">
			<%- flashes_to_show.each do |key| -%>
				<%= content_tag(:div, h(flash[key]), :class => "flash #{key}") if flash[key] -%>
			<%- end -%>
		</div>
	</div>
<% end %>

app/views/layouts/_javascript.html.erb
<%= javascript_include_tag(Rails.env.production? ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js' : '/javascripts/jquery.js') %>
<!--[if IE]><%= sprockets_include_tag 'excanvas' %><![endif]-->
<%= sprockets_include_tag 'application' %>


<% js_var :DEBUG, !Rails.env.production? %>
<% js_var :authenticity_token, form_authenticity_token %>
<%= javascript_include_tag 'i18n' %>

<%= yield :javascript %>

<%- if @content_for_dom_ready or @content_for_in_javascript -%>
	<script type="text/javascript">
	//<![CDATA[
		$(function() { <%= yield :dom_ready %> });
		<%= yield :in_javascript %>
	//]]>
	</script>
<% end %>


<% if Rails.env.production? then %>
	<script type="text/javascript">
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	</script>
	<script type="text/javascript">
	try {
	var pageTracker = _gat._getTracker("UA-1309955-12");
	pageTracker._trackPageview();
	} catch(err) {}</script>
<% end %>

app/views/layouts/_unobtrusive_hack.html.erb
<style type="text/css">
	.js .js-hide{ display: none; }
</style>
<script type="text/javascript">
	document.getElementsByTagName('html')[0].className += 'js';
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

  <title><%= render_title %></title>
  <meta name="Description" content="<%= yield :description -%>" />
  <meta name="Keywords" content="<%= yield :keywords -%>" />


  <%= render 'unobtrusive_hack' %>
  <%= stylesheet_link_tag 'application' %>

  <%= yield :head %>

  <meta http-equiv="X-UA-Compatible" content="IE=7" />
</head>
<body class="<%= body_class %>">

  <header>
    <h1><%= link_to 'Weatherham.com', root_path %></h1>
    <p>A visualization of weather patterns from <a href="http://bellcold.com">Bellingham Cold Storage</a>.</p>
  </header>

  <div id="wrapper">
    <%= render 'flashes' %>
    <%= yield %>
  </div>

  <footer>
    <p>
      Created by <%= link_to 'Amiel Martin', 'http://amielmartin.com' %>.
      Weather data provided by <%= link_to 'Bellingham Cold Storage', 'http://www.bellcold.com/download.txt', :rel => 'external' %>.
    </p>

    <p id="utc_warning">
      Labels for the x-axis on this graph are in UTC. This is a restriction of the graphing library, and I'm working on a fix for it.
    </p>

    <p>
      <%= link_to 'About Weatherham', about_path %> |
      <%= link_to 'CHANGELOG', changelog_path, rel: 'facebox', title: 'CHANGELOG' %> |
      <%= link_to 'TODO', todo_path, rel: 'facebox', title: 'TODO' %> |
      <%= link_to 'code', 'http://github.com/amiel/weatherham', :rel => 'external' %>
    </p>
  </footer>

  <%= render 'javascript' %>
</body>
</html>

app/views/layouts/application.iphone.erb
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Weatherham</title>
        <% javascript 'jqtouch' %>
        <% stylesheet 'vendor/jqtouch.css' %>      
        <% stylesheet 'vendor/jqtouch.theme.css' %>             
        
        <%= yield :head %>
        <%= yield :javascript %>        
        <script type="text/javascript">
        $.jQTouch({
            icon: '/images/jqtouch/jqtouch.png'
        });
        </script>
    </head>
    <body>
      <%= yield %>
    </body>
</html>

app/views/layouts/maintenance.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>OH NO</title>
</head>
<body>
	<h1></h1>
	<p></p>

</body>
</html>